### ISSUE TITLE
Suggestion: deprecate activeElement

### ISSUE THREAD

**Issue by ollema** [svecosystem/runed#100]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I suggest to deprecate and/or remove the `activeElement` utility and instead refer to the now builtin [`activeElement` binding on `<svelte:document>`](https://github.com/sveltejs/svelte/pull/11879).

Alternatively, the `activeElement` could be rewritten to reuse the new builtin binding if you would like to keep it.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://github.com/sveltejs/svelte/pull/11879

**Comment by TGlide** [comment]
Runed is meant to work outside of Svelte components as well, so we'll keep the utility, but a note in the docs would be helpful.

**Comment by notramo** [comment]
@TGlide, could you reopen this? The docs hasn't been updated yet.

Also worth mentioning the read-only `focused` binding which exists on every Element. It may be a cleaner solution for some use cases.
