### ISSUE TITLE
DoubleClick

### ISSUE THREAD

**Issue by TGlide** [svecosystem/runed#127]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

A double click action and/or helper that accepts an element.

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
Would this be an enhanced version of `ondblclick`?

**Comment by TGlide** [comment]
I didn't know ondblclick was a thing tbh

**Comment by huntabyte** [comment]
> I didn't know ondblclick was a thing tbh

Not going to lie, I just found out about it not too long ago when someone opened a PR for one of the libs to expose it as `on:dblclick`... 🤯

Think we're good to close this one on that note?

**Comment by TGlide** [comment]
Yup, closing!
