### ISSUE TITLE
How does Runed `Store` compare to `toStore` and `fromStore` recently added to Svelte 5?

### ISSUE THREAD

**Issue by Greenheart** [svecosystem/runed#135]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Thanks for this project - several good and useful utilities in here!

Now that Svelte 5 core has the functions `toStore` and `fromStore` similar to the `Store` utility from Runed, I'm wondering what this means for this library.

It would be useful to increase visibility that it's possible to work with stores and runes in the same project. Either through a thin wrapper in Runed, or just mentioning this in the docs. However, probably the best option is to just refer to the Svelte core docs.

What do you think?

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://svelte-5-preview.vercel.app/docs/imports#svelte-store

**Comment by huntabyte** [comment]
Yeah, we'll likely drop ours in favor of Svelte's unless there's a case @TGlide has for keeping them 😃

**Comment by TGlide** [comment]
Nope, we should definitely remove it!

**Comment by Greenheart** [comment]
Thanks for clarifying!

Closing since this was fixed by https://github.com/svecosystem/runed/pull/184
