### ISSUE TITLE
Debounced doesn't work with objects

### ISSUE THREAD

**Issue by LeanderG** [svecosystem/runed#160]
### Describe the bug

In this example, debouncedCount will be updated immediately. I would expect it to be debounced.

```
<script>
  import { Debounced } from "runed"
  let countObj = $state({count: 0})
  const increment = () => {
    countObj.count += 1
  }

 let debouncedCount = new Debounced(() => countObj, 1000);

</script>

<button onclick={increment}>
  count is {countObj.count}
</button>

debouncedCount is
{debouncedCount.current.count}

```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-33c6zp?file=src%2Flib%2FCounter.svelte

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    runed: ^0.16.1 => 0.16.1 
    svelte: ^5.3.1 => 5.4.0
```

### Severity

annoyance

**Comment by huntabyte** [comment]
That's because the object is deeply reactive.

If you were to declare it as `$state.raw()` it should work, otherwise you should depend on `obj.count` 😁

**Comment by LeanderG** [comment]
Thanks for the explanaition.

This is my use case:
I have a rune that holds all my form data. I want to pass the data to a library to do an expensive calculation which shouldn't happen on every keystroke.
I was hoping there is already a primitve out there that lets me debounce an entire object but I couldn't find one.

**Comment by huntabyte** [comment]
Here's how you could accomplish it :) [REPL](https://svelte.dev/playground/hello-world?version=5.6.1#H4sIAAAAAAAAE22Py26DMBBFf2U06gJURMmWBqSq3ecD6i7AmahOYIzsoQ9Z_vfK0CRK1ZWt6_s4DsjdSFjjC_V2Zk172PVH0oIFHsxAHuvXgPI9JU8SsDgnnqap9B80SNL6ztN_urYsxOKxxq3XzkzSKgYw42SdQIDrbISDsyModDPTXmGyDSSg7cyy64_QwJ2XTigLi1RDFfNk0pa9gGHtaCQWaCDLoWkhpEe45MvlAvcNbNJDVKx4GdifEZ4XQwNMn1eubC1bp0vP3eTfrWTn1ryATVVV-WOq2z5cvqh4288ilsGyHow-NeFCGNsVO60ZD-GWMKaeNbv0_MEzXnG41Uo9O0fp_M1jgUJfgrW4meJb_AGbKHR55QEAAA==)

**Comment by LeanderG** [comment]
Thanks, this works. The only downside is that in this [REPL](https://svelte.dev/playground/9a82b173c6b440278affba1ed22a673d?version=5.6.1) the $effect runs twice in the beginning.
