### ISSUE TITLE
`Previous.current` is confusing

### ISSUE THREAD

**Issue by notramo** [svecosystem/runed#176]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

`previous.current` suggests that it's the current value, not the retained one. While at first it doesn't really make sense as the current value can be read from the original store, it's still a viable source of confusion as one might think it's exposed for debugging purposes (e.g. debugging reactivity problems with complex nested objects).

I recommend changing it to `previous.value`.  While other alternatives like `.retained`, `.old`, or even `.previous` might seem more descriptive at first, we have to consider that in most cases the `Previous` instance is not named `previous`, but something else. Try to use the property name with some possible object names: `previousCursorPosition.value`, `oldSelectedItem.value`, `previousInputContent.value`

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
Thanks for opening this issue!

The decision to use `.current` is part of a broader pattern across Svelte's APIs, where `.current` consistently represents "the current value of this thing at this moment in time." This pattern appears in other Svelte utilities like reactive window values (`innerWidth.current`, `scrollY.current`), `MediaQuery`, and more.

While I understand that `.value` might feel more intuitive in isolation, changing it would create an inconsistency with related APIs. When using this utility, I've found it helpful to use variable names that make the intent clear, for example:

```ts
const prevCount = new Previous(() => count)
const prevValue = new Previous(() => value)
```

This way the variable name itself communicates that we're dealing with a previous value, while the `.current` accessor remains consistent with Svelte's other APIs.

For these reasons, we'll keep the existing `.current` convention.
