### ISSUE TITLE
Feature Request: useIntersectionObserver

### ISSUE THREAD

**Issue by sviripa** [svecosystem/runed#38]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

A utility function which provides a way to track visibility and position of a DOM element within the viewport or a container element. Under the hood it will use Intersection Observer API so it would expect to receive `IntersectionObserver`'s `root`, `margin`, and `threshold` options and would return an instance of `IntersectionObserverEntry`

### What type of pull request would this be?

None

### Provide relevant links or additional information.

- https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by huntabyte** [comment]
Closed by #73
