### ISSUE TITLE
Sharable rune primitives

### ISSUE THREAD

**Issue by th3l0g4n** [svecosystem/runed#93]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

This is exactly the kind of library svelte needs right now. Especially with the introduction of the new runes API.
As the current utilities are already loosely based on vue primitives, are you planning to introduce base primitives that make it easier to sharing state between componentes and hooks / composables?

I am thinking about equivalents for **ref** and **reactive** (maybe **computed**) in the vue reactivity system.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://vuejs.org/api/reactivity-core#ref
https://vuejs.org/api/reactivity-core#reactive
https://vuejs.org/api/reactivity-core#computed

**Comment by TGlide** [comment]
We did have these before, but don't think they're needed. Check our internals to see how we make do without refs, reactive or computed :)
